dist: xenial
services:
  - mysql
language: php
sudo: required
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - "/\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
php:
  - '5.6'
  - '7.2'
  - '7.3'
env:
  - WP_VERSION=latest
matrix:
  fast_finish: true
cache:
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - vendor
install:
  - composer install
  - ulimit -n 4096
before_script:
  - if php -v | grep -q 'Xdebug'; then phpenv config-rm xdebug.ini; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then pecl install pcov; fi
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then composer require phpunit/phpunit:^7 --ignore-platform-reqs --update-with-all-dependencies; composer require pcov/clobber --ignore-platform-reqs; vendor/bin/pcov clobber; vendor/bin/phpunit --configuration phpunit.xml --coverage-clover coverage.xml; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.3" ]]; then vendor/bin/phpunit --configuration phpunit.xml; fi
  - vendor/bin/phpcs --standard=phpcs.ruleset.xml *.php inc/ bin/
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - export TRAVIS_PROJECT_SLUG="$(basename $TRAVIS_BUILD_DIR)"
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - chmod +x wp-cli.phar
  - sudo mv wp-cli.phar /usr/local/bin/wp
  - wp package install wp-cli/dist-archive-command
  - composer install --no-dev --optimize-autoloader
  - cd ../
  - wp dist-archive $TRAVIS_PROJECT_SLUG $TRAVIS_BUILD_DIR/$TRAVIS_PROJECT_SLUG-$TRAVIS_TAG.zip
  - cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: TBXNSgy4xEtOyoFD3+C3tKgKWJI7tyQySC4W9lu9sBmg44sooqIW/zazwXtTaifi6CSRRZ0NLh8rBNyjYaupUfAMEhi4K0VMwR21fYpL+XxyGxlTQY1RbPhCGvFlfadgNFYKjMzRh+zv6Y+RyqNpHRRtN7coAPJOboPtuvC0XgN5D62AW7oh4eh+f4iylgnwnJqK1VIGAzQlcdH6IvIah7/SRJSbDbSFYUEGdHNPZrHG7Jd8TehESvDQq59SMBSnYas+xm/YzfNZK89tJgnhXvqILjWzT80kqEPGC2wrxaIdth5XWvw678k6TY9kUhduHzxwzwqZb/GfOiFo4L6eagA8V3+W0TlYFnj+kPH8ycLuA5+H1ZhOMJy7HAvQ5j3RhDyLEBllyjDYdNtC53+FrVe7mMm9kzfHe7YsffhiOgTPjd/ctrZbeWi1AUi/DubuZHORGSHKFyh1FLRUTy3ZXlWoaz1l7KPlT6orjvPvswZScXx9o1xegzXenh81Ws8QfsRuIhUGan/x7sC1jNh9ldSNEa6vAHNvmD80i7os7bmNqaZXGDhRYQUVNrI5/JzCyfbHzcfHlqizdOYcsPr+N/Ezl1Iatbs4f2KZ1iDkkzcBSl28m018tacsWU4qbPEMVGGzUpBGFE9osN359UrdoSUjO4OfsFiJs4bdi6O2Nhk=
  file: "parsedown-party-$TRAVIS_TAG.zip"
  on:
    tags: true
    repo: connerbw/parsedown-party