language: php
sudo: required
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
php:
- '7.0'
- '7.1'
- '5.6'
env:
- WP_VERSION=latest
matrix:
  fast_finish: true
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - vendor
install:
- composer install
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- vendor/bin/phpunit --configuration phpunit.xml --coverage-clover coverage.xml
- vendor/bin/phpcs --standard=phpcs.ruleset.xml *.php inc/ bin/
after_success:
- bash <(curl -s https://codecov.io/bash)